version: '3'
services:
  node-app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    volumes:
      - .:/var/www/app
  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db